// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogpostDocumentDataSlicesSlice = BlogTextBlockSlice | HeroSliceSlice;

/**
 * Content for Blogpost documents
 */
interface BlogpostDocumentData {
  /**
   * Title field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Category field in *Blogpost*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Independent Sponsor Insights"
    | "Deal Sourcing & Origination"
    | "Private Equity Strategies"
    | "Capital Raising & Investor Relations"
    | "Industry Trends"
    | "Thought Leadership"
    | "Resources & Guides"
  >;

  /**
   * Author field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Created at field in *Blogpost*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.created_at
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  created_at: prismic.DateField;

  /**
   * Excerpt field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Featured Image field in *Blogpost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Content field in *Blogpost*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Blogpost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogpost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blogpost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

type CareerDocumentDataSlicesSlice =
  | TextBlockSlice
  | CriteriaInfoSliceSlice
  | FirmOverviewSlice
  | BlogContentIndexSlice
  | FavouriteIndeustrySlice
  | BlogTextBlockSlice
  | HeroSliceSlice
  | CareerContentIndexSlice;

/**
 * Content for Career documents
 */
interface CareerDocumentData {
  /**
   * Title field in *Career*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Excerpt field in *Career*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Description field in *Career*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: career.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Department field in *Career*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Capital Markets
   * - **API ID Path**: career.department
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  department: prismic.SelectField<
    | "Capital Markets"
    | "Due Diligence"
    | "Investment Team"
    | "M&A/Origination"
    | "Public Markets/Hedge Funds"
    | "Technology"
    | "Deal Team"
    | "Operations",
    "filled"
  >;

  /**
   * Hire Level field in *Career*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: career.hire_level
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  hire_level: prismic.SelectField<
    | "Managing Director"
    | "Associate"
    | "Intern"
    | "Analyst"
    | "Vice President"
    | "Professional/Individual Contributor"
  >;

  /**
   * Status field in *Career*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: career.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<"Active" | "Hold" | "Passed" | "Upcoming">;

  /**
   * Slice Zone field in *Career*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: career.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CareerDocumentDataSlicesSlice> /**
   * Meta Title field in *Career*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: career.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Career*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: career.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Career*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: career.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Career document from Prismic
 *
 * - **API ID**: `career`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CareerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CareerDocumentData>, "career", Lang>;

/**
 * Item in *GrowthAreaPoints → Product and Engineering*
 */
export interface GrowthareapointsDocumentDataProductAndEngineeringItem {
  /**
   * Point field in *GrowthAreaPoints → Product and Engineering*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: growthareapoints.product_and_engineering[].point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  point: prismic.KeyTextField;
}

/**
 * Item in *GrowthAreaPoints → Team and Talent*
 */
export interface GrowthareapointsDocumentDataTeamAndTalentItem {
  /**
   * Point field in *GrowthAreaPoints → Team and Talent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: growthareapoints.team_and_talent[].point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  point: prismic.KeyTextField;
}

/**
 * Content for GrowthAreaPoints documents
 */
interface GrowthareapointsDocumentData {
  /**
   * Product and Engineering field in *GrowthAreaPoints*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: growthareapoints.product_and_engineering[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  product_and_engineering: prismic.GroupField<
    Simplify<GrowthareapointsDocumentDataProductAndEngineeringItem>
  >;

  /**
   * Team and Talent field in *GrowthAreaPoints*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: growthareapoints.team_and_talent[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_and_talent: prismic.GroupField<
    Simplify<GrowthareapointsDocumentDataTeamAndTalentItem>
  >;
}

/**
 * GrowthAreaPoints document from Prismic
 *
 * - **API ID**: `growthareapoints`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GrowthareapointsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GrowthareapointsDocumentData>,
    "growthareapoints",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = HeroSliceSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type OperatingmemberDocumentDataSlicesSlice =
  | LeftImageSliceSlice
  | HeroSliceSlice;

/**
 * Content for OperatingMember documents
 */
interface OperatingmemberDocumentData {
  /**
   * Name field in *OperatingMember*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operatingmember.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Designation field in *OperatingMember*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operatingmember.designation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designation: prismic.KeyTextField;

  /**
   * Image field in *OperatingMember*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operatingmember.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *OperatingMember*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operatingmember.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * LinkedinProfileLink field in *OperatingMember*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: operatingmember.linkedinprofilelink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedinprofilelink: prismic.LinkField;

  /**
   * Slice Zone field in *OperatingMember*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: operatingmember.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OperatingmemberDocumentDataSlicesSlice> /**
   * Meta Title field in *OperatingMember*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: operatingmember.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OperatingMember*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: operatingmember.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OperatingMember*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operatingmember.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OperatingMember document from Prismic
 *
 * - **API ID**: `operatingmember`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OperatingmemberDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OperatingmemberDocumentData>,
    "operatingmember",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | WorkingTeamIndexSlice
  | CareerContentIndexSlice
  | OperationTeamIndexSlice
  | TextBlockSlice
  | CriteriaInfoSliceSlice
  | TextWithBackgroundSlice
  | FirmOverviewSlice
  | FavouriteIndeustrySlice
  | CapabilitiesSlice
  | FocusAreasSlice
  | BlogContentIndexSlice
  | LeftImageSliceSlice
  | GrowthInvestmentAreaSlice
  | HowWeOperateSlice
  | ImpactInitiativesSlice
  | ContactHeroSlice
  | ContactFormSectionSlice
  | TeamIndexSlice
  | HeroSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * AppointmentButtonLink field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.appointmentbuttonlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  appointmentbuttonlink: prismic.LinkField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type TeammemberDocumentDataSlicesSlice =
  | LeftImageSliceSlice
  | TextBlockSlice
  | HeroSliceSlice;

/**
 * Content for TeamMember documents
 */
interface TeammemberDocumentData {
  /**
   * Name field in *TeamMember*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teammember.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Department field in *TeamMember*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: teammember.department
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  department: prismic.SelectField<
    | "Capital Markets"
    | "Deal Team"
    | "Legal & Compliance"
    | "Operations"
    | "M&A/Origination"
    | "Technology"
    | "Investor Relations"
    | "Public Markets/Hedge Fund"
    | "Investment Team"
    | "Due Diligence"
  >;

  /**
   * Level field in *TeamMember*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Analyst
   * - **API ID Path**: teammember.level
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  level: prismic.SelectField<
    | "Analyst"
    | "Associate"
    | "Vice President"
    | "Managing Director"
    | "Managing Partner"
    | "Senior Vice President"
    | "Senior Managing Director"
    | "Management"
    | "Attorney"
    | "Professional / Individual Contributor",
    "filled"
  >;

  /**
   * Description field in *TeamMember*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teammember.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * LinkedInProfileLink field in *TeamMember*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: teammember.linkedinprofilelink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedinprofilelink: prismic.LinkField;

  /**
   * Profile Image field in *TeamMember*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teammember.profile_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *TeamMember*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teammember.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeammemberDocumentDataSlicesSlice> /**
   * Meta Title field in *TeamMember*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: teammember.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *TeamMember*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: teammember.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *TeamMember*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teammember.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * TeamMember document from Prismic
 *
 * - **API ID**: `teammember`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeammemberDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TeammemberDocumentData>,
    "teammember",
    Lang
  >;

export type AllDocumentTypes =
  | BlogpostDocument
  | CareerDocument
  | GrowthareapointsDocument
  | HomepageDocument
  | OperatingmemberDocument
  | PageDocument
  | TeammemberDocument;

/**
 * Default variation for BlogContentIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogContentIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BlogContentIndex*
 */
type BlogContentIndexSliceVariation = BlogContentIndexSliceDefault;

/**
 * BlogContentIndex Shared Slice
 *
 * - **API ID**: `blog_content_index`
 * - **Description**: BlogContentIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogContentIndexSlice = prismic.SharedSlice<
  "blog_content_index",
  BlogContentIndexSliceVariation
>;

/**
 * Primary content in *BlogTextBlock → Primary*
 */
export interface BlogTextBlockSliceDefaultPrimary {
  /**
   * Title field in *BlogTextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_text_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date Published field in *BlogTextBlock → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_text_block.primary.date_published
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date_published: prismic.TimestampField;

  /**
   * Content field in *BlogTextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_text_block.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for BlogTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogTextBlock*
 */
type BlogTextBlockSliceVariation = BlogTextBlockSliceDefault;

/**
 * BlogTextBlock Shared Slice
 *
 * - **API ID**: `blog_text_block`
 * - **Description**: BlogTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogTextBlockSlice = prismic.SharedSlice<
  "blog_text_block",
  BlogTextBlockSliceVariation
>;

/**
 * Default variation for Capabilities Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CapabilitiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Capabilities*
 */
type CapabilitiesSliceVariation = CapabilitiesSliceDefault;

/**
 * Capabilities Shared Slice
 *
 * - **API ID**: `capabilities`
 * - **Description**: Capabilities
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CapabilitiesSlice = prismic.SharedSlice<
  "capabilities",
  CapabilitiesSliceVariation
>;

/**
 * Default variation for CareerContentIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CareerContentIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CareerContentIndex*
 */
type CareerContentIndexSliceVariation = CareerContentIndexSliceDefault;

/**
 * CareerContentIndex Shared Slice
 *
 * - **API ID**: `career_content_index`
 * - **Description**: CareerContentIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CareerContentIndexSlice = prismic.SharedSlice<
  "career_content_index",
  CareerContentIndexSliceVariation
>;

/**
 * Primary content in *ContactFormSection → Primary*
 */
export interface ContactFormSectionSliceDefaultPrimary {
  /**
   * Heading field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * ContactFormImage field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.contactformimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  contactformimage: prismic.ImageField<never>;
}

/**
 * Default variation for ContactFormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactFormSection*
 */
type ContactFormSectionSliceVariation = ContactFormSectionSliceDefault;

/**
 * ContactFormSection Shared Slice
 *
 * - **API ID**: `contact_form_section`
 * - **Description**: ContactFormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSlice = prismic.SharedSlice<
  "contact_form_section",
  ContactFormSectionSliceVariation
>;

/**
 * Primary content in *ContactHero → Primary*
 */
export interface ContactHeroSliceDefaultPrimary {
  /**
   * Heading field in *ContactHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ContactHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_hero.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Background Image field in *ContactHero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for ContactHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactHero*
 */
type ContactHeroSliceVariation = ContactHeroSliceDefault;

/**
 * ContactHero Shared Slice
 *
 * - **API ID**: `contact_hero`
 * - **Description**: ContactHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSlice = prismic.SharedSlice<
  "contact_hero",
  ContactHeroSliceVariation
>;

/**
 * Default variation for CriteriaInfoSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CriteriaInfoSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CriteriaInfoSlice*
 */
type CriteriaInfoSliceSliceVariation = CriteriaInfoSliceSliceDefault;

/**
 * CriteriaInfoSlice Shared Slice
 *
 * - **API ID**: `criteria_info_slice`
 * - **Description**: CriteriaInfoSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CriteriaInfoSliceSlice = prismic.SharedSlice<
  "criteria_info_slice",
  CriteriaInfoSliceSliceVariation
>;

/**
 * Default variation for FavouriteIndustry Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FavouriteIndeustrySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FavouriteIndustry*
 */
type FavouriteIndeustrySliceVariation = FavouriteIndeustrySliceDefault;

/**
 * FavouriteIndustry Shared Slice
 *
 * - **API ID**: `favourite_indeustry`
 * - **Description**: FavouriteIndeustry
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FavouriteIndeustrySlice = prismic.SharedSlice<
  "favourite_indeustry",
  FavouriteIndeustrySliceVariation
>;

/**
 * Primary content in *FirmOverview → Primary*
 */
export interface FirmOverviewSliceDefaultPrimary {
  /**
   * Firm Overview Content field in *FirmOverview → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: firm_overview.primary.firm_overview_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  firm_overview_content: prismic.RichTextField;

  /**
   * Firm Strategy Content field in *FirmOverview → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: firm_overview.primary.firm_strategy_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  firm_strategy_content: prismic.RichTextField;
}

/**
 * Default variation for FirmOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirmOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FirmOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FirmOverview*
 */
type FirmOverviewSliceVariation = FirmOverviewSliceDefault;

/**
 * FirmOverview Shared Slice
 *
 * - **API ID**: `firm_overview`
 * - **Description**: FirmOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirmOverviewSlice = prismic.SharedSlice<
  "firm_overview",
  FirmOverviewSliceVariation
>;

/**
 * Default variation for FocusAreas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FocusAreasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FocusAreas*
 */
type FocusAreasSliceVariation = FocusAreasSliceDefault;

/**
 * FocusAreas Shared Slice
 *
 * - **API ID**: `focus_areas`
 * - **Description**: FocusAreas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FocusAreasSlice = prismic.SharedSlice<
  "focus_areas",
  FocusAreasSliceVariation
>;

/**
 * Default variation for GrowthInvestmentArea Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrowthInvestmentAreaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *GrowthInvestmentArea*
 */
type GrowthInvestmentAreaSliceVariation = GrowthInvestmentAreaSliceDefault;

/**
 * GrowthInvestmentArea Shared Slice
 *
 * - **API ID**: `growth_investment_area`
 * - **Description**: GrowthInvestmentArea
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrowthInvestmentAreaSlice = prismic.SharedSlice<
  "growth_investment_area",
  GrowthInvestmentAreaSliceVariation
>;

/**
 * Primary content in *HeroSlice → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Heading field in *HeroSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *HeroSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Background Image field in *HeroSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * BigHeight field in *HeroSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_slice.primary.bigheight
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  bigheight: prismic.BooleanField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *HowWeOperate → Primary*
 */
export interface HowWeOperateSliceDefaultPrimary {
  /**
   * Heading field in *HowWeOperate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_operate.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *HowWeOperate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_operate.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Strategy_Content field in *HowWeOperate → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_operate.primary.strategy_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  strategy_content: prismic.RichTextField;
}

/**
 * Primary content in *HowWeOperate → Items*
 */
export interface HowWeOperateSliceDefaultItem {
  /**
   * Experience Point field in *HowWeOperate → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_operate.items[].experience_point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_point: prismic.KeyTextField;

  /**
   * Benefit Point field in *HowWeOperate → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_operate.items[].benefit_point
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  benefit_point: prismic.KeyTextField;
}

/**
 * Default variation for HowWeOperate Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowWeOperateSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowWeOperateSliceDefaultPrimary>,
  Simplify<HowWeOperateSliceDefaultItem>
>;

/**
 * Slice variation for *HowWeOperate*
 */
type HowWeOperateSliceVariation = HowWeOperateSliceDefault;

/**
 * HowWeOperate Shared Slice
 *
 * - **API ID**: `how_we_operate`
 * - **Description**: HowWeOperate
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowWeOperateSlice = prismic.SharedSlice<
  "how_we_operate",
  HowWeOperateSliceVariation
>;

/**
 * Primary content in *ImpactInitiatives → Items*
 */
export interface ImpactInitiativesSliceDefaultItem {
  /**
   * Initiative Heading field in *ImpactInitiatives → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_initiatives.items[].initiative_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  initiative_heading: prismic.KeyTextField;

  /**
   * Initiative Tagline field in *ImpactInitiatives → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_initiatives.items[].initiative_tagline
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  initiative_tagline: prismic.LinkField;
}

/**
 * Default variation for ImpactInitiatives Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImpactInitiativesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImpactInitiativesSliceDefaultItem>
>;

/**
 * Slice variation for *ImpactInitiatives*
 */
type ImpactInitiativesSliceVariation = ImpactInitiativesSliceDefault;

/**
 * ImpactInitiatives Shared Slice
 *
 * - **API ID**: `impact_initiatives`
 * - **Description**: ImpactInitiatives
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImpactInitiativesSlice = prismic.SharedSlice<
  "impact_initiatives",
  ImpactInitiativesSliceVariation
>;

/**
 * Primary content in *LeftImageSlice → Primary*
 */
export interface LeftImageSliceSliceDefaultPrimary {
  /**
   * LeftImage field in *LeftImageSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: left_image_slice.primary.leftimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  leftimage: prismic.ImageField<never>;

  /**
   * Description field in *LeftImageSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: left_image_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image left? field in *LeftImageSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: left_image_slice.primary.image_left
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_left: prismic.BooleanField;

  /**
   * Image Circle field in *LeftImageSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: left_image_slice.primary.image_circle
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_circle: prismic.BooleanField;

  /**
   * Page Link field in *LeftImageSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: left_image_slice.primary.page_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_link: prismic.LinkField;

  /**
   * ShowLearnMoreButton field in *LeftImageSlice → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: left_image_slice.primary.showlearnmorebutton
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  showlearnmorebutton: prismic.BooleanField;
}

/**
 * Default variation for LeftImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftImageSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeftImageSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LeftImageSlice*
 */
type LeftImageSliceSliceVariation = LeftImageSliceSliceDefault;

/**
 * LeftImageSlice Shared Slice
 *
 * - **API ID**: `left_image_slice`
 * - **Description**: LeftImageSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftImageSliceSlice = prismic.SharedSlice<
  "left_image_slice",
  LeftImageSliceSliceVariation
>;

/**
 * Primary content in *OperationTeamIndex → Items*
 */
export interface OperationTeamIndexSliceDefaultItem {
  /**
   * Name field in *OperationTeamIndex → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operation_team_index.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *OperationTeamIndex → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operation_team_index.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Designation field in *OperationTeamIndex → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operation_team_index.items[].designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designation: prismic.KeyTextField;

  /**
   * LinkedInProfileLink field in *OperationTeamIndex → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: operation_team_index.items[].linkedinprofilelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedinprofilelink: prismic.LinkField;
}

/**
 * Default variation for OperationTeamIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OperationTeamIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<OperationTeamIndexSliceDefaultItem>
>;

/**
 * Slice variation for *OperationTeamIndex*
 */
type OperationTeamIndexSliceVariation = OperationTeamIndexSliceDefault;

/**
 * OperationTeamIndex Shared Slice
 *
 * - **API ID**: `operation_team_index`
 * - **Description**: OperationTeamIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OperationTeamIndexSlice = prismic.SharedSlice<
  "operation_team_index",
  OperationTeamIndexSliceVariation
>;

/**
 * Primary content in *TeamIndex → Items*
 */
export interface TeamIndexSliceDefaultItem {
  /**
   * Member Name field in *TeamIndex → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.items[].member_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_name: prismic.KeyTextField;

  /**
   * Member Position field in *TeamIndex → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.items[].member_position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_position: prismic.KeyTextField;

  /**
   * Member Image field in *TeamIndex → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.items[].member_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  member_image: prismic.ImageField<never>;

  /**
   * LinkedIn Link field in *TeamIndex → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_index.items[].linkedin_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkField;
}

/**
 * Default variation for TeamIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TeamIndexSliceDefaultItem>
>;

/**
 * Slice variation for *TeamIndex*
 */
type TeamIndexSliceVariation = TeamIndexSliceDefault;

/**
 * TeamIndex Shared Slice
 *
 * - **API ID**: `team_index`
 * - **Description**: TeamIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamIndexSlice = prismic.SharedSlice<
  "team_index",
  TeamIndexSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Main Content field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.main_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Primary content in *TextWithBackground → Primary*
 */
export interface TextWithBackgroundSliceDefaultPrimary {
  /**
   * BackgroundImage field in *TextWithBackground → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.primary.backgroundimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundimage: prismic.ImageField<never>;

  /**
   * Heading field in *TextWithBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *TextWithBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_background.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for TextWithBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextWithBackground*
 */
type TextWithBackgroundSliceVariation = TextWithBackgroundSliceDefault;

/**
 * TextWithBackground Shared Slice
 *
 * - **API ID**: `text_with_background`
 * - **Description**: TextWithBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithBackgroundSlice = prismic.SharedSlice<
  "text_with_background",
  TextWithBackgroundSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataSlicesSlice,
      CareerDocument,
      CareerDocumentData,
      CareerDocumentDataSlicesSlice,
      GrowthareapointsDocument,
      GrowthareapointsDocumentData,
      GrowthareapointsDocumentDataProductAndEngineeringItem,
      GrowthareapointsDocumentDataTeamAndTalentItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      OperatingmemberDocument,
      OperatingmemberDocumentData,
      OperatingmemberDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      TeammemberDocument,
      TeammemberDocumentData,
      TeammemberDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogContentIndexSlice,
      BlogContentIndexSliceVariation,
      BlogContentIndexSliceDefault,
      BlogTextBlockSlice,
      BlogTextBlockSliceDefaultPrimary,
      BlogTextBlockSliceVariation,
      BlogTextBlockSliceDefault,
      CapabilitiesSlice,
      CapabilitiesSliceVariation,
      CapabilitiesSliceDefault,
      CareerContentIndexSlice,
      CareerContentIndexSliceVariation,
      CareerContentIndexSliceDefault,
      ContactFormSectionSlice,
      ContactFormSectionSliceDefaultPrimary,
      ContactFormSectionSliceVariation,
      ContactFormSectionSliceDefault,
      ContactHeroSlice,
      ContactHeroSliceDefaultPrimary,
      ContactHeroSliceVariation,
      ContactHeroSliceDefault,
      CriteriaInfoSliceSlice,
      CriteriaInfoSliceSliceVariation,
      CriteriaInfoSliceSliceDefault,
      FavouriteIndeustrySlice,
      FavouriteIndeustrySliceVariation,
      FavouriteIndeustrySliceDefault,
      FirmOverviewSlice,
      FirmOverviewSliceDefaultPrimary,
      FirmOverviewSliceVariation,
      FirmOverviewSliceDefault,
      FocusAreasSlice,
      FocusAreasSliceVariation,
      FocusAreasSliceDefault,
      GrowthInvestmentAreaSlice,
      GrowthInvestmentAreaSliceVariation,
      GrowthInvestmentAreaSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      HowWeOperateSlice,
      HowWeOperateSliceDefaultPrimary,
      HowWeOperateSliceDefaultItem,
      HowWeOperateSliceVariation,
      HowWeOperateSliceDefault,
      ImpactInitiativesSlice,
      ImpactInitiativesSliceDefaultItem,
      ImpactInitiativesSliceVariation,
      ImpactInitiativesSliceDefault,
      LeftImageSliceSlice,
      LeftImageSliceSliceDefaultPrimary,
      LeftImageSliceSliceVariation,
      LeftImageSliceSliceDefault,
      OperationTeamIndexSlice,
      OperationTeamIndexSliceDefaultItem,
      OperationTeamIndexSliceVariation,
      OperationTeamIndexSliceDefault,
      TeamIndexSlice,
      TeamIndexSliceDefaultItem,
      TeamIndexSliceVariation,
      TeamIndexSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextWithBackgroundSlice,
      TextWithBackgroundSliceDefaultPrimary,
      TextWithBackgroundSliceVariation,
      TextWithBackgroundSliceDefault,
    };
  }
}
