// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  contact_hero: dynamic(() => import("./ContactHero")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  team_index: dynamic(() => import("./TeamIndex")),
};
