// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_content_index: dynamic(() => import("./BlogContentIndex")),
  capabilities: dynamic(() => import("./Capabilities")),
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  contact_hero: dynamic(() => import("./ContactHero")),
  criteria_info_slice: dynamic(() => import("./CriteriaInfoSlice")),
  favourite_indeustry: dynamic(() => import("./FavouriteIndustry")),
  firm_overview: dynamic(() => import("./FirmOverview")),
  focus_areas: dynamic(() => import("./FocusAreas")),
  growth_investment_area: dynamic(() => import("./GrowthInvestmentArea")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  how_we_operate: dynamic(() => import("./HowWeOperate")),
  impact_initiatives: dynamic(() => import("./ImpactInitiatives")),
  left_image_slice: dynamic(() => import("./LeftImageSlice")),
  operation_team_index: dynamic(() => import("./OperationTeamIndex")),
  team_index: dynamic(() => import("./TeamIndex")),
  text_block: dynamic(() => import("./TextBlock")),
  text_with_background: dynamic(() => import("./TextWithBackground")),
};
